### ISSUE TITLE
tabular data/ noisy instances 

### ISSUE THREAD

**Issue by nazaretl** [arghosh/RobustMW-Net#2]
Hi,
thanks for sharing your implementation. I have two questions about it:

1.	Does it also work on tabular data?
2.	Is it possible to identify the noisy instances (return the noisy IDs or the clean set).

Thanks!

**Comment by arghosh** [comment]
1. "Tabular data": Do you mean mix of categorical features and real-valued features? This repo works with image data with real-valued features. However, you can use standard datasets, tabular datasets by changing the input (e.g., one-hot encoding, embedding layers) and the layers (fully connected instead of convolutional). 
2. You can predict based on the weighting network [score](https://github.com/arghosh/RobustMW-Net/blob/main/trainer.py#L136). Use validation set to get the score threshold (for clean vs noisy) and the best epoch (to be used for returning the IDs).

**Comment by nazaretl** [comment]
many thanks!
